Create a list of possible feature vectors. Since features have weights, it is best to assign them values -1 and 1, so that features with -1 and 1 are placed as far apart as possible. Multiply them with weights so we can form clusters considering those weights. 

In [29]:
import itertools
lst = list(itertools.product([-1, 1], repeat=8))
wt_lst = [100000, 1000, 100, 10, 1000, 10, 100, 1000]
lst_of_vectors = list()


for feature_vector in lst:
    a_vector = list()
    for x, elem in enumerate(feature_vector):
        a_vector.append(elem * (wt_lst[x]))
    lst_of_vectors.append(a_vector)
print lst_of_vectors

[[-100000, -1000, -100, -10, -1000, -10, -100, -1000], [-100000, -1000, -100, -10, -1000, -10, -100, 1000], [-100000, -1000, -100, -10, -1000, -10, 100, -1000], [-100000, -1000, -100, -10, -1000, -10, 100, 1000], [-100000, -1000, -100, -10, -1000, 10, -100, -1000], [-100000, -1000, -100, -10, -1000, 10, -100, 1000], [-100000, -1000, -100, -10, -1000, 10, 100, -1000], [-100000, -1000, -100, -10, -1000, 10, 100, 1000], [-100000, -1000, -100, -10, 1000, -10, -100, -1000], [-100000, -1000, -100, -10, 1000, -10, -100, 1000], [-100000, -1000, -100, -10, 1000, -10, 100, -1000], [-100000, -1000, -100, -10, 1000, -10, 100, 1000], [-100000, -1000, -100, -10, 1000, 10, -100, -1000], [-100000, -1000, -100, -10, 1000, 10, -100, 1000], [-100000, -1000, -100, -10, 1000, 10, 100, -1000], [-100000, -1000, -100, -10, 1000, 10, 100, 1000], [-100000, -1000, -100, 10, -1000, -10, -100, -1000], [-100000, -1000, -100, 10, -1000, -10, -100, 1000], [-100000, -1000, -100, 10, -1000, -10, 100, -1000], [-100000, 

In [30]:
from sklearn.cluster import KMeans
import numpy as np
X = np.array(lst_of_vectors)
X

array([[-100000,   -1000,    -100, ...,     -10,    -100,   -1000],
       [-100000,   -1000,    -100, ...,     -10,    -100,    1000],
       [-100000,   -1000,    -100, ...,     -10,     100,   -1000],
       ..., 
       [ 100000,    1000,     100, ...,      10,    -100,    1000],
       [ 100000,    1000,     100, ...,      10,     100,   -1000],
       [ 100000,    1000,     100, ...,      10,     100,    1000]])

In [32]:
kmeans = KMeans(n_clusters=2, random_state=0).fit(X)
kmeans.labels_

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0], dtype=int32)

If we have people with *all* different choices and there are only two clusters possible, they should be put in different clusters. Let's verify. 

In [36]:
kmeans.predict([[-100000, -1000, -100, -10, -1000, -10, -100, -1000]])

array([1], dtype=int32)

In [37]:
kmeans.predict([[100000, 1000, 100, 10, 1000, 10, 100, 1000]])

array([0], dtype=int32)

In [15]:
kmeans.cluster_centers_

array([[ 0.75,  0.5 ,  0.5 ,  0.5 ,  0.5 ,  0.5 ,  0.75,  0.75],
       [ 0.25,  0.5 ,  0.5 ,  0.5 ,  0.5 ,  0.5 ,  0.25,  0.25]])

Create about 1000 users with random preferences. Predict their clusters. For every 5 members in a cluster, form a group. 

In [ ]:
random_lst_1 = [lst_of_vectors[1]]*200
random_lst_2 = [lst_of_vectors[58]]*200
random_lst_3 = [lst_of_vectors[100]]*200
random_lst_4 = [lst_of_vectors[198]]*200
random_lst_5 = [lst_of_vectors[200]]*200
random_lst = random_lst_1 + random_lst_2 +random_lst_3 +random_lst_4+random_lst_5
random_lst

In [55]:
dict_of_clusters = dict()
all_results = list()
for each_user in random_lst:
    all_results.append(kmeans.predict([each_user]).tostring())

print(all_results)

['\x01\x00\x00\x00', '\x01\x00\x00\x00', '\x01\x00\x00\x00', '\x01\x00\x00\x00', '\x01\x00\x00\x00', '\x01\x00\x00\x00', '\x01\x00\x00\x00', '\x01\x00\x00\x00', '\x01\x00\x00\x00', '\x01\x00\x00\x00', '\x01\x00\x00\x00', '\x01\x00\x00\x00', '\x01\x00\x00\x00', '\x01\x00\x00\x00', '\x01\x00\x00\x00', '\x01\x00\x00\x00', '\x01\x00\x00\x00', '\x01\x00\x00\x00', '\x01\x00\x00\x00', '\x01\x00\x00\x00', '\x01\x00\x00\x00', '\x01\x00\x00\x00', '\x01\x00\x00\x00', '\x01\x00\x00\x00', '\x01\x00\x00\x00', '\x01\x00\x00\x00', '\x01\x00\x00\x00', '\x01\x00\x00\x00', '\x01\x00\x00\x00', '\x01\x00\x00\x00', '\x01\x00\x00\x00', '\x01\x00\x00\x00', '\x01\x00\x00\x00', '\x01\x00\x00\x00', '\x01\x00\x00\x00', '\x01\x00\x00\x00', '\x01\x00\x00\x00', '\x01\x00\x00\x00', '\x01\x00\x00\x00', '\x01\x00\x00\x00', '\x01\x00\x00\x00', '\x01\x00\x00\x00', '\x01\x00\x00\x00', '\x01\x00\x00\x00', '\x01\x00\x00\x00', '\x01\x00\x00\x00', '\x01\x00\x00\x00', '\x01\x00\x00\x00', '\x01\x00\x00\x00', '\x01\x00\x00\x00',

OK some ugly bytes result. Cant help it for now. Will leave. Will group similar items together like so:
https://stackoverflow.com/a/30294172/6613065

In [64]:
from collections import Counter
counts = Counter(all_results)
print counts
clusters =  [ [k,]*v for k,v in counts.items()]
clusters

Counter({'\x01\x00\x00\x00': 600, '\x00\x00\x00\x00': 400})


[['\x00\x00\x00\x00',
  '\x00\x00\x00\x00',
  '\x00\x00\x00\x00',
  '\x00\x00\x00\x00',
  '\x00\x00\x00\x00',
  '\x00\x00\x00\x00',
  '\x00\x00\x00\x00',
  '\x00\x00\x00\x00',
  '\x00\x00\x00\x00',
  '\x00\x00\x00\x00',
  '\x00\x00\x00\x00',
  '\x00\x00\x00\x00',
  '\x00\x00\x00\x00',
  '\x00\x00\x00\x00',
  '\x00\x00\x00\x00',
  '\x00\x00\x00\x00',
  '\x00\x00\x00\x00',
  '\x00\x00\x00\x00',
  '\x00\x00\x00\x00',
  '\x00\x00\x00\x00',
  '\x00\x00\x00\x00',
  '\x00\x00\x00\x00',
  '\x00\x00\x00\x00',
  '\x00\x00\x00\x00',
  '\x00\x00\x00\x00',
  '\x00\x00\x00\x00',
  '\x00\x00\x00\x00',
  '\x00\x00\x00\x00',
  '\x00\x00\x00\x00',
  '\x00\x00\x00\x00',
  '\x00\x00\x00\x00',
  '\x00\x00\x00\x00',
  '\x00\x00\x00\x00',
  '\x00\x00\x00\x00',
  '\x00\x00\x00\x00',
  '\x00\x00\x00\x00',
  '\x00\x00\x00\x00',
  '\x00\x00\x00\x00',
  '\x00\x00\x00\x00',
  '\x00\x00\x00\x00',
  '\x00\x00\x00\x00',
  '\x00\x00\x00\x00',
  '\x00\x00\x00\x00',
  '\x00\x00\x00\x00',
  '\x00\x00\x00\x00',
  '\x00\x0

So these are the two groups. Woot. Long way to just get their names. Sure could've done better. Should group these together into groups of 5. On a leg and a prayer...

In [68]:
lst_of_groups = list()
for cluster in clusters:
    lst_within_a_cluster = list()
    for low in range(0, len(cluster)-5):
        lst_within_a_cluster.append(cluster[low: low+5])
        low += 5
    lst_of_groups.append(lst_within_a_cluster)
print len(lst_of_groups[1])  
print len(lst_of_groups[0])

595
395


Kind of good!